### ISSUE TITLE
What happens if a user tries to create a household with the same name?

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#13]
Will it cause an error or create it? Overwrite the description? Dumb the old household?

**Comment by bradwarrum** [comment]
It will create the household with the same name and a different ID.  If you want to check that a household does not exist with the name already for a user, that can be implemented client side. However, it's a bit difficult to detect households that are named the same when users start getting invited to other households, because it will become a duplication when members are added, not when the household is created

**Comment by gsczechowski** [comment]
Ah, that makes sense. I will need to add some safety guards client side since I am not necessarily super careful about that. But I should be able to work with it I think.
