### ISSUE TITLE
Is fractional still relevant?

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#18]
Shopping list API doesn't have fractional returning, Inventory does.

**Comment by gsczechowski** [comment]
Follow up: get inventory and get shopping list are very different response which may cause client side issues when moving items from one to the other

**Comment by bradwarrum** [comment]
Inventory is set up currently so that when you link the UPC or create a new UPC, you describe the units of measurement for the packaging itself.  The inventory retrieval call contains the packaging information so that users have access to the information if they want to change it by re-linking a UPC.

Shopping list and recipe calls quantities are in terms of packaging.  It was assumed that you will not buy fractional portions of an item when you go to the store, so the only field available for list calls is quantity.

Recipes quantities are currently in terms of package quantities. We will need to have a discussion on what the best plan of action is, since many recipes call for unit types that are different from what the packaging is labeled as.

**Comment by bradwarrum** [comment]
Packaging information is now available for list requests

**Comment by bradwarrum** [comment]
Fractional components now supported on shopping lists.
